### ISSUE TITLE
retrieve output from leetcode for custom cases

### ISSUE THREAD

**Issue by j178** [j178/leetgo#101]
For user provided test cases, the expected output can be left blank, we submit the code (must can be compiled) to leetcode to retrieve the output, and write it back to `input.txt`

ref: https://github.com/j178/leetgo/pull/90#issuecomment-1416735809

**Comment by w43322** [comment]
Do we need to sanitize this? What if a user provides a test case with the wrong output

**Comment by j178** [comment]
> Do we need to sanitize this? What if a user provides a test case with the wrong output

We can't tell, wrong output will get wrong result, user will recognize it.



> do we need to sanitize the input to make sure it's legal

Not necessary I think, LeetCode will report an error if it's illegal, we just need to show the error to user.
