### ISSUE TITLE
C++ local test support

### ISSUE THREAD

**Issue by j178** [j178/leetgo#11]

**Comment by w43322** [comment]
working on this

**Comment by j178** [comment]
Thanks a lot! If you have any issues about the code, welcome to contact~

Generally local test support of a language requires three part of work:
1. **testing enviroment initialization**. Creating a workspace so that langauge specific testing tool can be runned.
2. **testing code generation**, like `solution_test.go` file in Go.
3. **test supporting library**, this library will be introduced in the testing code, it will do some preparation work (like deserializing a binary tree), call the solution function, then compare the results.

**Comment by w43322** [comment]
关于SPJ的问题

有些题目（如0001.two-sum）的返回结果顺序可以是乱序的，请问这个是如何处理的？在已有的代码中没看到关于给结果排序的逻辑，是否需要单独实现一下

**Comment by j178** [comment]
old-yan recommended his project to me, will do some research: https://github.com/old-yan/CP-template/blob/main/IO/LeetcodeIO.h

**Comment by w43322** [comment]
pr should be ready by the weekend (hopefully)
