### ISSUE TITLE
support better answer judgement

### ISSUE THREAD

**Issue by j178** [j178/leetgo#110]
1. judgement for questions without return value, they change the input parameter in-place, like https://leetcode.cn/problems/reorder-list/
2. judgement for random order sequence, like https://leetcode.cn/problems/two-sum/,

**Comment by w43322** [comment]
Another kind of problem: the output string is not standard
https://leetcode.cn/problems/linked-list-cycle-ii/

**Comment by j178** [comment]
> 1. judgement for questions without return value, they change the input parameter in-place, like https://leetcode.cn/problems/reorder-list/

For this type of questions, there is actually a `paramindex` in questions' metadata:
```
{
  "name": "reorderList",
  "params": [
    {
      "name": "head",
      "type": "ListNode"
    }
  ],
  "return": {
    "type": "void"
  },
  "output": {
    "paramindex": 0
  }
}
```
we can use this info to serialize the corresponding paramater as output.

**Comment by j178** [comment]
a new special case: https://leetcode.cn/problems/find-positive-integer-solution-for-a-given-equation/
this function takes a function as first parameter 🤯

**Comment by w43322** [comment]
https://leetcode.cn/problems/first-bad-version/comments/

Also there are problems with pre-defined APIs.

**Comment by j178** [comment]
We can use a little script to get some hints about these pre-definied function:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/10510431/220006030-6c07f5bc-d018-4b1a-98db-4fb7cdf8d98b.png">
