### ISSUE TITLE
add `leetgo open` to open question page in browser

### ISSUE THREAD

**Issue by j178** [j178/leetgo#113]
`leetgo open today` to open today question in browser. Should support contest questions as well `leetgo open w122`.

**Comment by forestmgy** [comment]
I use leetgo to do some leetcode questions recently, I'd like to help with this issue.
But I need some time to familiarize myself with the source code : )

**Comment by j178** [comment]
Sure, thanks for offering your help! Please don't hesitate to reach out if you have any questions or issues with the code.

I'm also curious to hear your thoughts on using this tool. Let me know if you have any feedback or suggestions.
