### ISSUE TITLE
[Feature] No "bits/stdc++.h" in macOS/clang

### ISSUE THREAD

**Issue by w43322** [j178/leetgo#138]
### Verify steps

- [X]  我已经在 [Issue Tracker](https://github.com/j178/leetgo/issues) 中找过我要提出的请求 I have searched on the [Issue Tracker](https://github.com/j178/leetgo/issues) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/j178/leetgo/blob/master/README.md) 并无法自行解决问题 I have read the [Documentation](https://github.com/j178/leetgo/blob/master/README.md) and was unable to solve the issue. 

### Description

`bits/stdc++.h` is a gnu/gcc extension, which is not present in macOS/clang. 

https://stackoverflow.com/questions/28994148/how-can-i-include-bits-stdc-in-xcode

Should we fix this rather than letting the users fix this for themselves?

### Possible Solution

```cpp
#ifndef __APPLE__
    #include <bits/stdc++.h>
#else
    // insert #include directives here, or make a copy of gcc's bits/stdc++.h
#endif
```

**Comment by j178** [comment]
Since we are emulating the LeetCode OJ, I think we should ship the `bits/stdc++.h` for macOS version. Like this one: https://github.com/tekfyl/bits-stdc-.h-for-mac/blob/master/stdc%2B%2B.h

**Comment by j178** [comment]
It's better to create a separate PR.

**Comment by w43322** [comment]
We can use this command to fetch the latest `stdc++.h` directly from gcc's source repo:
`git archive --remote=git://gcc.gnu.org/git/gcc.git HEAD libstdc++-v3/include/precompiled/stdc++.h | tar -xO`

**Comment by w43322** [comment]
What if we run this command on the user's machine?

**Comment by j178** [comment]
> What if we run this command on the user's machine?

I don't think we should do this automatically. Instead, we should add some instructions to our manual and let the users handle it themselves. Alternatively, we can simply have Mac users run `brew install gcc` :)
