### ISSUE TITLE
feat: switch between lccn and lcus more conveniently

### ISSUE THREAD

**Issue by w43322** [j178/leetgo#151]

**Comment by w43322** [comment]
how about a new cli flag `-s --site [cn | us]` @j178

**Comment by w43322** [comment]
or `-a --alternative-site`

**Comment by j178** [comment]
I would prefer `-s --site [cn | us]`.

Actually there is a `LEETGO_SITE` env var to switch site, but it is a little tedious too. If we added `-s —site`, `LEETGO_SITE` should be removed too.

**Comment by w43322** [comment]
I agree
