### ISSUE TITLE
[Bug] brew upgrade leetgo 之后，leetgo 无法使用

### ISSUE THREAD

**Issue by zwyyy456** [j178/leetgo#201]
### Verify steps

- [X]  我已经在 [Issue Tracker](https://github.com/j178/leetgo/issues) 和 [Discussion](https://github.com/j178/leetgo/discussions) 中找过我要提出的问题 I have searched on the [Issue Tracker](https://github.com/j178/leetgo/issues) and [Discussion](https://github.com/j178/leetgo/discussions) for a related issue. 

### leetgo debug

```shell
❯ leetgo debug
× unmarshal config failed: 2 error(s) decoding:

* 'code.cpp.cxxflags' expected type 'string', got unconvertible type '[]interface {}', value: '[-O2 -std=c++17]'
* 'editor.args' expected type 'string', got unconvertible type '[]interface {}', value: '[]'
(base)
```

### Description

在执行 `brew upgrade leetgo` 来将 leetgo 更新到最新之后，leetgo 无法正常使用，执行 `leetgo debug` 或者 `leetgo pick 1143` 都会出现如下报错：
```sh
× unmarshal config failed: 2 error(s) decoding:

* 'code.cpp.cxxflags' expected type 'string', got unconvertible type '[]interface {}', value: '[-O2 -std=c++17]'
* 'editor.args' expected type 'string', got unconvertible type '[]interface {}', value: '[]'
```

执行 `leetgo -v` 输出如下：
```sh
leetgo version 1.3.1
commit: 92f1dd0a70c124d5506b95f8690e302180bff3f2
built at: 2023-06-14T13:25:11Z
goos: darwin
goarch: arm64

https://github.com/j178/leetgo
(base)
```

**Comment by j178** [comment]
你好，1.0 版本修改了 `code.cpp.cxxflags` 和 `editor.args` 的格式，在 release note 中有说明解决方法：https://github.com/j178/leetgo/releases/tag/v1.0

1. 手动在 `~/.config/leetgo/config.yaml` 中修改 `code.cpp.cxxflags` 和 `editor.args` 为字符串
2. 或者直接删掉 `~/.config/leetgo/config.yaml`, 然后重新执行 `leetgo init`
