### ISSUE TITLE
[Feature] If the local test run fails, it should return a non-zero return value

### ISSUE THREAD

**Issue by xiantang** [j178/leetgo#215]
### Verification steps

- [X]  我已经在 [Issue Tracker](https://github.com/j178/leetgo/issues) 中找过我要提出的请求 I have searched on the [Issue Tracker](https://github.com/j178/leetgo/issues) for a related feature request. 

### Description

<img width="675" alt="image" src="https://github.com/j178/leetgo/assets/34479567/63c323ad-584c-43bf-9789-1cc917c1a9dd">
In this case, the return value of "echo "$?"" should be 127

**Comment by j178** [comment]
Thanks for the report, I fixed it in #216 by return `1` if any test case failed. Exit code 127 means job's command can not be found or executed, which is not suitable.
