### ISSUE TITLE
leetgo test now truncates too much... [Bug] 

### ISSUE THREAD

**Issue by JesseGuerrero** [j178/leetgo#264]
### leetgo debug

NA

### Debug log

```shell
NA
```

### Description

Thank you for all you do, I love leetgo so far!

When there is an error, the stdout is truncated and new lines are not used, take a look:
![image](https://github.com/j178/leetgo/assets/27308928/d3593cad-156d-4943-ba53-e26f2d5548f3)

I cant debug my leetcode solutions anymore. For now I will be using an older version.

But yes, its a good idea to check if its an error so its not truncated and also potential carriage returns are new lines if you wanted that.

**Comment by j178** [comment]
Thanks for the report!

This issue has been fixed in the master branch but not released yet, might get to a release very soon, stay tuned!

**Comment by j178** [comment]
Hi, [v1.4](https://github.com/j178/leetgo/releases/tag/v1.4) is out, please try it out, thanks!

**Comment by JesseGuerrero** [comment]
Wow dude thanks!
