### ISSUE TITLE
[Bug] Local testing for python doesnt take None type

### ISSUE THREAD

**Issue by JesseGuerrero** [j178/leetgo#265]
### leetgo debug

NA

### Debug log

```shell
NA
```

### Description

![image](https://github.com/j178/leetgo/assets/27308928/d1ab8090-05ea-4ff2-8c1c-01f8ca4c4393)
I returned a None type and it doesnt parse through it in parse.py for ListNode type questions.

To replicate this, try to return None in merge-two-sorted-lists

**Comment by j178** [comment]
Thanks for the report!
