### ISSUE TITLE
[Bug] Submit - empty body

### ISSUE THREAD

**Issue by lmenale** [j178/leetgo#308]
### leetgo debug

leetgo submit 18
● reading leetcode cookies browser=edge domain=leetcode.com
● submitting solution question=4sum user=lmenale@leetcode.com

 ✔ Accepted

Passed cases:  294/294
Runtime:       385 ms, better than 81%
Memory:        16.8 MB, better than 6%
● retry url=https://leetcode.com/graphql/noj-go/ attempt=0 error="[400 Bad Request] <empty body>"
● retry url=https://leetcode.com/graphql/noj-go/ attempt=1 error="[400 Bad Request] <empty body>"
● retry url=https://leetcode.com/graphql/noj-go/ attempt=2 error="[400 Bad Request] <empty body>"

### Description

As you can see from the output, when I submit I receive this error.

**Comment by j178** [comment]
This is primarily due to an invalid cookie. Could you please provide the complete debug log?
