### ISSUE TITLE
Support more browsers

### ISSUE THREAD

**Issue by j178** [j178/leetgo#74]
- [x] Firefox
- [x] Edge
- [x] Safari

**Comment by Mamong** [comment]
when to support firefox?

**Comment by j178** [comment]
@Mamong fiefox support has been added in #79 , will be released soon after some tests. Would you like to help testing it?

**Comment by Mamong** [comment]
@j178 ok, i will try it later.Thanks!

**Comment by Mamong** [comment]
@j178  firefox works
