### ISSUE TITLE
failed to run leetgo init

### ISSUE THREAD

**Issue by ismdeep** [j178/leetgo#92]
```
[INFO]  global config file created: file=/home/ljiang/.config/leetgo/config.yaml
[INFO]  project config file created: file=leetgo.yaml
Error: open /home/ljiang/.config/leetgo/cache/leetcode-questions.db: no such file or directory
```

**Comment by j178** [comment]
Hi, I can't reproduce this on my side actually.

May I ask what's the version you are using? Are you building from source with `CGO_ENABLED=1`?
I am asking because from your error, the cache file is `leetcode-questions.db`, which is only possible when you build it with cgo enabled.

**Comment by ismdeep** [comment]
By default, there is no `~/.config/leetgo` directory on the system. However, when you run the `leetgo init` command, the `~/.config/leetgo` directory is automatically created but not the `~/.config/leetgo/cache` directory.

**Comment by j178** [comment]
Right, we do create the cache directory during init, but only for the default JSON cache implementation:
https://github.com/j178/leetgo/blob/ba77f558549cc8e0a7a1ce7d680fef1b32799067/leetcode/cache_json.go#L85-L89
not in the sqlite implementation.

Thanks for your report.

**Comment by ismdeep** [comment]
You could merge my pull request to solve the bug.

**Comment by j178** [comment]
merged, thanks.
